### ISSUE TITLE
Fix tokenizer bug: token includes final space

### ISSUE THREAD

**Issue by dkaisr** [dkaisr/minishell#16]
If i type in `echo Hello World`, i get the tokens
'echo ', 'Hello ', and 'World'. 
The space should not be included in the token. Please fix!

**Comment by dkaisr** [comment]
Found another, maybe related bug: redirs directly after a pipe don't work.
Example: `echo Hello World|> out.txt cat -e`

**Comment by cuhlig42** [comment]
is fixed
